# Generated by Django 5.0.4 on 2024-04-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_news_item_comment_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='text',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
