# Generated by Django 5.0.4 on 2024-04-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_parentcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='newsItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.newsitem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='api.comment'),
        ),
    ]
