# Generated by Django 5.0.4 on 2024-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_options_alter_newsitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-time_create']},
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='text',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='news_link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
